# Generated by Django 2.2 on 2019-09-08 06:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24, unique=True)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 9, 8, 12, 25, 19, 186576))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 9, 8, 12, 25, 19, 194736))),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Author')),
            ],
        ),
    ]
